### ISSUE TITLE
Sentry reported issues

### ISSUE THREAD

**Issue by ferostabio** [Fujicracy/fuji-v2#609]
- [ ] ```Error: Invariant: attempted to hard navigate to the same URL /my-positions https://app.fuji.finance/my-positions
  at Error: Invariant: attempted to hard navigate to the same URL /my-positions  (https://app.fuji.finance/my-positions)
  at Generator.throw (<anonymous>)```
- [ ] ```TypeError: e.fuel.addConnector is not a function
  at W (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/pageScript-69e5fb36.js:1:4249)
  at None (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/pageScript-69e5fb36.js:1:4286)```

- [ ] ``` TypeError: Cannot read properties of undefined (reading 'providerName')
  at None (chrome-extension://kglcipoddmbniebnibibkghfijekllbl/js/inject.bundle.js:1:5926)
``` (In the `/borrow` page)
- [x] input same id
- [x] chart same key
- [x] Error rendering BorrowHeader while redirecting

**Comment by ferostabio** [comment]
This one just happened one time on Friday, while a user was on the `/borrow` page. @NikolaiYurchenko please have a quick look to see if there's anything we might have missed!

**Comment by NikolaiYurchenko** [comment]
Couldnt reproduce old ones, but found and fixed few more.
Context: 
- in analytics chart data we were formatting date to local and it causes case where 2 last points has same date and not showed correctly (were on same dot and if you do a little move with mouse different data is shown) so I changed to show in UTC to avoid this
- ids for both inputs on borrow were same, so causes error in console
- When we were at my-positions/:id and navigating to /borow we got error that BorrowHeader cant change state during BorrowPage render
